import {
  Pill,
  Flame,
  Trophy,
  Star,
  Sparkles,
  PenLine,
  HeartPulse,
  Rainbow,
  Flag,
  PartyPopper,
  Eye,
  Droplet,
  Droplets,
  Users,
  UsersRound,
  Camera,
  MessageCircle,
  Footprints,
  Handshake,
  Compass,
  Anchor,
  Landmark,
  Crown,
  Zap,
  Target,
  Lock,
  Hand,
  Clock,
  Gem,
  CalendarCheck,
  CheckCircle2,
  HandHeart,
  Moon,
  Hourglass,
  ShieldCheck,
  Gauge,
  Sunrise,
  ThumbsUp,
  Lightbulb,
  Battery,
  Mail,
  Wind,
  Dumbbell,
  TrendingUp,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  pill: Pill,
  flame: Flame,
  trophy: Trophy,
  star: Star,
  sparkles: Sparkles,
  pen: PenLine,
  heart_pulse: HeartPulse,
  rainbow: Rainbow,
  flag: Flag,
  party: PartyPopper,
  eye: Eye,
  droplet: Droplet,
  droplets: Droplets,
  users: Users,
  users_round: UsersRound,
  camera: Camera,
  message: MessageCircle,
  message_circle: MessageCircle,
  footprints: Footprints,
  handshake: Handshake,
  compass: Compass,
  anchor: Anchor,
  landmark: Landmark,
  crown: Crown,
  zap: Zap,
  target: Target,
  lock: Lock,
  hand: Hand,
  clock: Clock,
  gem: Gem,
  calendar_check: CalendarCheck,
  check_circle: CheckCircle2,
  hand_heart: HandHeart,
  moon: Moon,
  hourglass: Hourglass,
  shield_check: ShieldCheck,
  gauge: Gauge,
  sunrise: Sunrise,
  thumbs_up: ThumbsUp,
  battery: Battery,
  lightbulb: Lightbulb,
  mail: Mail,
  check: CheckCircle2,
  wind: Wind,
  dumbbell: Dumbbell,
  trending_up: TrendingUp,
}

/** Dados antigos podem ter emoji direto — sem entrada aqui, cai no fallback (texto cru). */
export function getCollectibleIcon(key: string): LucideIcon | null {
  return ICON_MAP[key] ?? null
}
